name: build

on:
  push:
    branches:
      - master

env:
  IMAGE_NOTEBOOKS: docker.pkg.github.com/${{ github.repository }}/kubeflow-dataverk-base
  IMAGE_PIPELINES: docker.pkg.github.com/${{ github.repository }}/kubeflow-dataverk-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create tag
        run: echo ::set-env name=IMAGE_TAG::$(date +%Y-%m-%d)--$(git rev-parse --short HEAD)
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Build notebook base docker image
        run: docker build -t ${IMAGE_NOTEBOOKS}:${IMAGE_TAG} -f notebooks/Dockerfile_notebooks .
      - name: Push notebook base docker image
        run: docker push ${IMAGE_NOTEBOOKS}:${IMAGE_TAG}
      - name: Build pipeline base docker image
        run: docker build -t ${IMAGE_PIPELINES}:${IMAGE_TAG} -f pipelines/Dockerfile_pipelines .
      - name: Push pipeline base docker image
        run: docker push ${IMAGE_PIPELINES}:${IMAGE_TAG}
